// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfvzmhopjzdtgflnrrvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdnptaG9wanpkdGdmbG5ycnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODg1NzcsImV4cCI6MjA2ODA2NDU3N30.EHA0WZgrniLLdIg4DtxerrLliR0lR9Iv_80_x4vlGBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});